### ISSUE TITLE
update_marc_record_service_spec.rb needs refactoring to cut down on repetition

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/item-release#36]
lots of setup repeated from test to test.
https://github.com/sul-dlss/item-release/blob/master/spec/lib/dor/update_marc_record_service_spec.rb

**Comment by blalbrit** [comment]
See also #sul-dlss/discovery-indexing/1

**Comment by peetucket** [comment]
fixed some of this when this logic was moved to dor-services-app (https://github.com/sul-dlss/dor-services-app)
