### ISSUE TITLE
"Bulk Action" and item-release are no longer working together

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/item-release#98]
Individual item-release in Argo is working currently, but the "Bulk Action" management of release has stopped working within the last week.

Attaching recent logs from jobs that fail to run in bulk. If this should be in Argo instead, please do go ahead and move it.

This is a blocker for our users.

[log (16).txt](https://github.com/sul-dlss/item-release/files/2385567/log.16.txt)
[log (15).txt](https://github.com/sul-dlss/item-release/files/2385568/log.15.txt)

**Comment by blalbrit** [comment]
By contrast, attached are two logs for individual item release jobs that do work:
[log (18).txt](https://github.com/sul-dlss/item-release/files/2385569/log.18.txt)
[log (17).txt](https://github.com/sul-dlss/item-release/files/2385570/log.17.txt)

**Comment by cbeer** [comment]
https://app.honeybadger.io/projects/49894/faults/39504601#notice-summary:

```
ActiveFedora::ObjectNotFoundError: Unable to find 'mt454vk9918' in fedora. See logger for details.
```

**Comment by blalbrit** [comment]
https://argo.stanford.edu/view/druid:mt454vk9918

**Comment by blalbrit** [comment]
Embarrassingly, yes. Thanks @jcoyne - I should have caught that, but I appreciate your sleuthing.
